# Generated by Django 4.0.1 on 2022-01-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rok', '0001__initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commanders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commander', models.CharField(blank=True, max_length=255, null=True)),
                ('rarity', models.CharField(choices=[('legendary', 'Legendary'), ('epic', 'Epic'), ('elite', 'Elite'), ('advanced', 'Advanced')], max_length=30, null=True)),
                ('rokclass', models.CharField(choices=[('infantry', 'Infantry'), ('cavalry', 'Cavalry'), ('archer', 'Archer')], max_length=30, null=True)),
                ('star_level', models.CharField(choices=[('one', 'One'), ('two', 'Two'), ('three', 'Three'), ('four', 'Four'), ('five', 'Five'), ('six', 'Six')], max_length=30, null=True)),
                ('specialty1', models.CharField(choices=[('infantry', 'Infantry'), ('cavalry', 'Cavalry'), ('archer', 'Archer'), ('leadership', 'Leadership'), ('peacekeeping', 'PeaceKeeping'), ('versatility', 'Versatility'), ('integration', 'Integration'), ('garrison', 'Garrison'), ('conquering', 'Conquering'), ('skill', 'Skill'), ('attack', 'Attack'), ('defense', 'Defense'), ('mobility', 'Mobility'), ('support', 'Support'), ('gathering', 'Gathering')], max_length=30, null=True)),
                ('specialty2', models.CharField(choices=[('infantry', 'Infantry'), ('cavalry', 'Cavalry'), ('archer', 'Archer'), ('leadership', 'Leadership'), ('peacekeeping', 'PeaceKeeping'), ('versatility', 'Versatility'), ('integration', 'Integration'), ('garrison', 'Garrison'), ('conquering', 'Conquering'), ('skill', 'Skill'), ('attack', 'Attack'), ('defense', 'Defense'), ('mobility', 'Mobility'), ('support', 'Support'), ('gathering', 'Gathering')], max_length=30, null=True)),
                ('specialty3', models.CharField(choices=[('infantry', 'Infantry'), ('cavalry', 'Cavalry'), ('archer', 'Archer'), ('leadership', 'Leadership'), ('peacekeeping', 'PeaceKeeping'), ('versatility', 'Versatility'), ('integration', 'Integration'), ('garrison', 'Garrison'), ('conquering', 'Conquering'), ('skill', 'Skill'), ('attack', 'Attack'), ('defense', 'Defense'), ('mobility', 'Mobility'), ('support', 'Support'), ('gathering', 'Gathering')], max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='count',
        ),
    ]
