# Generated by Django 4.0.1 on 2022-01-27 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rok', '0002_commanders_delete_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commanders',
            new_name='Commander',
        ),
    ]
