# Generated by Django 4.0.1 on 2022-01-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rok', '0003_rename_commanders_commander'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(blank=True, max_length=255, null=True)),
                ('wood', models.CharField(blank=True, max_length=255, null=True)),
                ('stone', models.CharField(blank=True, max_length=255, null=True)),
                ('gold', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='commander',
            name='rokclass',
            field=models.CharField(choices=[('infantry', 'Infantry'), ('cavalry', 'Cavalry'), ('archer', 'Archer'), ('mixed', 'Mixed')], max_length=30, null=True),
        ),
    ]
