# Generated by Django 4.0.1 on 2022-01-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rok', '0004_resource_alter_commander_rokclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacksmith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leather', models.CharField(blank=True, max_length=255, null=True)),
                ('iron_ore', models.CharField(blank=True, max_length=255, null=True)),
                ('animal_bone', models.CharField(blank=True, max_length=255, null=True)),
                ('ebony', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
