# Generated by Django 4.0.1 on 2022-01-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rok', '0005_blacksmith'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='gems',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
