# Generated by Django 4.0.1 on 2022-01-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rok', '0007_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speedup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_speedup', models.CharField(choices=[('1_minute', '1_Minute'), ('5_minutes', '5_Minutes'), ('10_minutes', '10_Minutes'), ('15_minutes', '15_Minutes'), ('30_minutes', '30_Minutes'), ('60_minutes', '60_Minutes'), ('3_hours', '3_Hours'), ('8_hours', '8_Hours'), ('15_hours', '15_Hours'), ('24_hours', '24_Hours')], max_length=30, null=True)),
                ('bquantity', models.CharField(blank=True, max_length=255, null=True)),
                ('traing_speedup', models.CharField(choices=[('1_minute', '1_Minute'), ('5_minutes', '5_Minutes'), ('10_minutes', '10_Minutes'), ('15_minutes', '15_Minutes'), ('30_minutes', '30_Minutes'), ('60_minutes', '60_Minutes'), ('3_hours', '3_Hours'), ('8_hours', '8_Hours'), ('15_hours', '15_Hours'), ('24_hours', '24_Hours')], max_length=30, null=True)),
                ('tquantity', models.CharField(blank=True, max_length=255, null=True)),
                ('research_speedup', models.CharField(choices=[('1_minute', '1_Minute'), ('5_minutes', '5_Minutes'), ('10_minutes', '10_Minutes'), ('15_minutes', '15_Minutes'), ('30_minutes', '30_Minutes'), ('60_minutes', '60_Minutes'), ('3_hours', '3_Hours'), ('8_hours', '8_Hours'), ('15_hours', '15_Hours'), ('24_hours', '24_Hours')], max_length=30, null=True)),
                ('rquantity', models.CharField(blank=True, max_length=255, null=True)),
                ('healing_speedup', models.CharField(choices=[('1_minute', '1_Minute'), ('5_minutes', '5_Minutes'), ('10_minutes', '10_Minutes'), ('15_minutes', '15_Minutes'), ('30_minutes', '30_Minutes'), ('60_minutes', '60_Minutes'), ('3_hours', '3_Hours'), ('8_hours', '8_Hours'), ('15_hours', '15_Hours'), ('24_hours', '24_Hours')], max_length=30, null=True)),
                ('hquantity', models.CharField(blank=True, max_length=255, null=True)),
                ('universal_speedup', models.CharField(choices=[('1_minute', '1_Minute'), ('5_minutes', '5_Minutes'), ('10_minutes', '10_Minutes'), ('15_minutes', '15_Minutes'), ('30_minutes', '30_Minutes'), ('60_minutes', '60_Minutes'), ('3_hours', '3_Hours'), ('8_hours', '8_Hours'), ('15_hours', '15_Hours'), ('24_hours', '24_Hours')], max_length=30, null=True)),
                ('uquantity', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
