# Generated by Django 4.0.1 on 2022-01-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rok', '0008_speedup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedup',
            name='building_speedup',
            field=models.CharField(choices=[('1 minute', '1 Minute'), ('5 minutes', '5 Minutes'), ('10 minutes', '10 Minutes'), ('15 minutes', '15 Minutes'), ('30 minutes', '30 Minutes'), ('60 minutes', '60 Minutes'), ('3 hours', '3 Hours'), ('8 hours', '8 Hours'), ('15 hours', '15 Hours'), ('24 hours', '24 Hours')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='speedup',
            name='healing_speedup',
            field=models.CharField(choices=[('1 minute', '1 Minute'), ('5 minutes', '5 Minutes'), ('10 minutes', '10 Minutes'), ('15 minutes', '15 Minutes'), ('30 minutes', '30 Minutes'), ('60 minutes', '60 Minutes'), ('3 hours', '3 Hours'), ('8 hours', '8 Hours'), ('15 hours', '15 Hours'), ('24 hours', '24 Hours')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='speedup',
            name='research_speedup',
            field=models.CharField(choices=[('1 minute', '1 Minute'), ('5 minutes', '5 Minutes'), ('10 minutes', '10 Minutes'), ('15 minutes', '15 Minutes'), ('30 minutes', '30 Minutes'), ('60 minutes', '60 Minutes'), ('3 hours', '3 Hours'), ('8 hours', '8 Hours'), ('15 hours', '15 Hours'), ('24 hours', '24 Hours')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='speedup',
            name='traing_speedup',
            field=models.CharField(choices=[('1 minute', '1 Minute'), ('5 minutes', '5 Minutes'), ('10 minutes', '10 Minutes'), ('15 minutes', '15 Minutes'), ('30 minutes', '30 Minutes'), ('60 minutes', '60 Minutes'), ('3 hours', '3 Hours'), ('8 hours', '8 Hours'), ('15 hours', '15 Hours'), ('24 hours', '24 Hours')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='speedup',
            name='universal_speedup',
            field=models.CharField(choices=[('1 minute', '1 Minute'), ('5 minutes', '5 Minutes'), ('10 minutes', '10 Minutes'), ('15 minutes', '15 Minutes'), ('30 minutes', '30 Minutes'), ('60 minutes', '60 Minutes'), ('3 hours', '3 Hours'), ('8 hours', '8 Hours'), ('15 hours', '15 Hours'), ('24 hours', '24 Hours')], max_length=30, null=True),
        ),
    ]
