# Generated by Django 4.0.1 on 2022-01-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rok', '0009_alter_speedup_building_speedup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expanded_training', models.CharField(choices=[('lvl 1', 'Lvl 1'), ('lvl 2', 'Lvl 2'), ('lvl 3', 'Lvl 3'), ('lvl 4', 'Lvl 4'), ('lvl 5', 'Lvl 5'), ('lvl 6', 'Lvl 6')], max_length=30, null=True)),
                ('peace_shield', models.CharField(choices=[('8 hours', '8 Hours'), ('24 hours', '24 Hours')], max_length=30, null=True)),
                ('enhanced_gathering', models.CharField(choices=[('8 hours', '8 Hours'), ('24 hours', '24 Hours')], max_length=30, null=True)),
                ('enhanced_attack', models.CharField(choices=[('12 hours', '12 Hours'), ('24 hours', '24 Hours')], max_length=30, null=True)),
                ('enhanced_defense', models.CharField(choices=[('12 hours', '12 Hours'), ('24 hours', '24 Hours')], max_length=30, null=True)),
                ('anti_reconnaissance_technology', models.CharField(blank=True, max_length=255, null=True)),
                ('deceptive_troops', models.CharField(blank=True, max_length=255, null=True)),
                ('army_expansion', models.CharField(choices=[('25%', '25%'), ('50%', '50%')], max_length=30, null=True)),
                ('food_boost', models.CharField(choices=[('8 hours', '8 Hours'), ('24 hours', '24 Hours')], max_length=30, null=True)),
                ('wood_boost', models.CharField(choices=[('8 hours', '8 Hours'), ('24 hours', '24 Hours')], max_length=30, null=True)),
                ('stone_boost', models.CharField(choices=[('8 hours', '8 Hours'), ('24 hours', '24 Hours')], max_length=30, null=True)),
                ('gold_boost', models.CharField(choices=[('8 hours', '8 Hours'), ('24 hours', '24 Hours')], max_length=30, null=True)),
            ],
        ),
    ]
