# Generated by Django 4.0.1 on 2022-01-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rok', '0010_boost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_1', models.CharField(blank=True, max_length=255, null=True)),
                ('tier_2', models.CharField(blank=True, max_length=255, null=True)),
                ('tier_3', models.CharField(blank=True, max_length=255, null=True)),
                ('tier_4', models.CharField(blank=True, max_length=255, null=True)),
                ('tier_5', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
